---
# Номер основного договора
contract_num: "7-P/19"

# Дата основного договора
contract_date: "«25» сентября 2019 г."

# Номер дополнительного соглашения
sup_num: "2"

# Дата дополнительного соглашения
sup_date: "«9» июня 2020 г."

# Часовая ставка
hour_rate: 1000

# Имя файла docx шаблона
template_filename: act_v1
